### ISSUE TITLE
Bazel test failed: bhive_importer_test

### ISSUE THREAD

**Issue by 9Tempest** [google/gematria#18] opened 2023-09-19 16:31 UTC
Hi, after building gematria (`bazel build ...`), I run `bazel test ...`, but failed at `bhive_importer_test.test_x86_parse_csv_line`, and the error log indicate that
```bash
e_importer_test/test.log 
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //gematria/datasets/python:bhive_importer_test
-----------------------------------------------------------------------------
Running tests under Python 3.10.0: /home/gematria/gematria_env/bin/python3
[ RUN      ] BhiveImporterTest.test_x86_basic_block_proto_from_bytes
[       OK ] BhiveImporterTest.test_x86_basic_block_proto_from_bytes
[ RUN      ] BhiveImporterTest.test_x86_basic_block_proto_from_hex
[       OK ] BhiveImporterTest.test_x86_basic_block_proto_from_hex
[ RUN      ] BhiveImporterTest.test_x86_nonstandard_columns
[       OK ] BhiveImporterTest.test_x86_nonstandard_columns
[ RUN      ] BhiveImporterTest.test_x86_parse_csv_line
[  FAILED  ] BhiveImporterTest.test_x86_parse_csv_line
======================================================================
ERROR: test_x86_parse_csv_line (__main__.BhiveImporterTest)
BhiveImporterTest.test_x86_parse_csv_line
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lukez/.cache/bazel/_bazel_lukez/6ec059981b607312b48b2c4811597fe7/sandbox/linux-sandbox/6/execroot/com_google_gematria/bazel-out/k8-fastbuild/bin/gematria/datasets/python/bhive_importer_test.runfiles/com_google_gematria/gematria/datasets/python/bhive_importer_test.py", line 203, in test_x86_parse_csv_line
    block_proto = importer.basic_block_with_throughput_proto_from_csv_line(
TypeError: basic_block_with_throughput_proto_from_csv_line(): incompatible function arguments. The following argument types are supported:
    1. (self: gematria.datasets.python.bhive_importer.BHiveImporter, source_name: str, line: str, machine_code_hex_column_index: int, throughput_column_index: int, throughput_scaling: float = 1.0, base_address: int = 0) -> gematria::BasicBlockWithThroughputProto

Invoked with: <gematria.datasets.python.bhive_importer.BHiveImporter object at 0x7ffb153321f0>; kwargs: source_name='test: made-up', line='4829d38b44246c8b54246848c1fb034829d04839c3,10', base_address=600, throughput_scaling=2.0

----------------------------------------------------------------------
Ran 4 tests in 0.069s

FAILED (errors=1)
```

Do you know how to address this issue?  The machine I am using is a Intel Broadwell in x86.

**Comment by boomanaiden154** [comment] 2023-09-20 05:45
The specific architecture here shouldn't matter as that test just uses parses a CSV file into a protobuf for use elsewhere within Gematria, and this looks like an issue with pybind.

I can reproduce this issue in the docker image. Not sure exactly what's causing it as it was working when I last hacked on that section of the code and the build should be relatively hermetic. I'll work on investigating/bisecting this when I get a chance.

**Comment by ondrasej** [comment] 2023-09-22 19:15
@9Tempest Thanks for reporting this!

By looking at the error, it seems that we're missing `machine_code_hex_column_index` and `throughput_column_index` in the `basic_block_with_throughput_proto_from_csv_line` call: https://github.com/google/gematria/blob/22428f9e7ccb2e697fb39a5c5a6fe025d86a9e46/gematria/datasets/python/bhive_importer_test.py#L203.

This is now fixed in https://github.com/google/gematria/commit/22428f9e7ccb2e697fb39a5c5a6fe025d86a9e46.

**Closed by ondrasej** 2023-09-22 19:15 UTC
